{% set name = "sphinx-fortran" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/VACUMM/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: c99bb776c8702a67232624221afbde280159f26121aa2116f6aec5ebe00e24b8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - future
    - numpy >=1.0
    - python >={{ python_min }}
    - six
    - sphinx >=1.0

test:
  imports:
    - sphinxfortran
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://sphinx-fortran.readthedocs.org
  dev_url: https://github.com/VACUMM/sphinx-fortran
  summary: Fortran domain and autodoc extensions to Sphinx
  license:  CECILL-2.1
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - awvwgk
